insert into product (prodCategory, prodName, prodOnHand, prodPAR, prodPrice) values ('Beverage', 'Coffee - Espresso', 1, 2, '$13.87');
insert into product (prodCategory, prodName, prodOnHand, prodPAR, prodPrice) values ('Grocery', 'Tomato - Peeled Italian Canned', 4, 7, '$12.75');
insert into product (prodCategory, prodName, prodOnHand, prodPAR, prodPrice) values ('Equipment', 'Vaccum Bag - 14x20', 2, 24, '$2.42');
insert into product (prodCategory, prodName, prodOnHand, prodPAR, prodPrice) values ('Equipment', 'Glass - Juice Clear 5oz 55005', 2, 7, '$10.07');
insert into product (prodCategory, prodName, prodOnHand, prodPAR, prodPrice) values ('P&P', 'Garbag Bags - Black', 2, 1, '$28.19');
insert into product (prodCategory, prodName, prodOnHand, prodPAR, prodPrice) values ('Grocery', 'Broccoli - Fresh', 5, 16, '$19.33');
insert into product (prodCategory, prodName, prodOnHand, prodPAR, prodPrice) values ('Beverage', 'Hot Choc Vending', 2, 9, '$20.73');
insert into product (prodCategory, prodName, prodOnHand, prodPAR, prodPrice) values ('Grocery', 'Oil - Food, Lacquer Spray', 2, 23, '$13.14');
insert into product (prodCategory, prodName, prodOnHand, prodPAR, prodPrice) values ('Meat', 'Pork - Smoked Kassler', 4, 12, '$4.69');
insert into product (prodCategory, prodName, prodOnHand, prodPAR, prodPrice) values ('Grocery''Beans - Navy, Dry', 4, 25, '$3.83');
insert into product (prodCategory, prodName, prodOnHand, prodPAR, prodPrice) values ('Grocery', 'Flower - Dish Garden', 5, 24, '$4.21');
insert into product (prodCategory, prodName, prodOnHand, prodPAR, prodPrice) values ('Grocery', 'Pie Pecan', 4, 20, '$4.13');
insert into product (prodCategory, prodName, prodOnHand, prodPAR, prodPrice) values ('Grocery', 'Food Colouring - Pink', 5, 6, '$34.48');
insert into product (prodCategory, prodName, prodOnHand, prodPAR, prodPrice) values ('Grocery', 'Soup - Campbells', 1, 12, '$30.97');
insert into product (prodCategory, prodName, prodOnHand, prodPAR, prodPrice) values ('Grocery', 'Muffin Mix - Banana Nut', 2, 24, '$23.55');
insert into product (prodCategory, prodName, prodOnHand, prodPAR, prodPrice) values ('Grocery', 'Lemon Tarts', 5, 23, '$24.05');
insert into product (prodCategory, prodName, prodOnHand, prodPAR, prodPrice) values ('Beverage', 'Jagermeister', 4, 25, '$1.34');
insert into product (prodCategory, prodName, prodOnHand, prodPAR, prodPrice) values ('Grocery', 'Spinach - Baby', 4, 16, '$15.28');
insert into product (prodCategory, prodName, prodOnHand, prodPAR, prodPrice) values ('Equipment', 'Table Cloth 62x120 Colour', 4, 12, '$4.39');
insert into product (prodCategory, prodName, prodOnHand, prodPAR, prodPrice) values ('Grocery', 'Cookies - Englishbay Chochip', 4, 1, '$7.89');
insert into product (prodCategory, prodName, prodOnHand, prodPAR, prodPrice) values ('Grocery', 'Sauce - Hollandaise', 3, 18, '$17.12');
insert into product (prodCategory, prodName, prodOnHand, prodPAR, prodPrice) values ('Muffin - Carrot Individual Wrap', 5, 21, '$9.14');
insert into product (prodCategory, prodName, prodOnHand, prodPAR, prodPrice) values ('Grocery', 'Dc - Frozen Momji', 5, 21, '$14.80');
insert into product (prodCategory, prodName, prodOnHand, prodPAR, prodPrice) values ('Grocery', 'Browning Caramel Glace', 2, 22, '$20.86');
insert into product (prodCategory, prodName, prodOnHand, prodPAR, prodPrice) values ('Meat', 'Beef - Ground Medium', 5, 13, '$22.71');
insert into product (prodCategory, prodName, prodOnHand, prodPAR, prodPrice) values ('Grocery', 'Soup - Campbells, Butternut', 3, 19, '$10.36');
insert into product (prodCategory, prodName, prodOnHand, prodPAR, prodPrice) values ('Grocery', 'Oil - Olive', 2, 5, '$2.28');
insert into product (prodCategory, prodName, prodOnHand, prodPAR, prodPrice) values ('Grocery', 'Orange - Canned, Mandarin', 5, 19, '$8.48');
insert into product (prodCategory, prodName, prodOnHand, prodPAR, prodPrice) values ('Beverage', 'Puree - Mocha', 3, 17, '$14.18');
insert into product (prodCategory, prodName, prodOnHand, prodPAR, prodPrice) values ('Bakery', 'Bread - Italian Roll With Herbs', 2, 25, '$28.45');
